# Generated by Django 4.1.3 on 2022-11-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_tecnologias_empresa_logo_empresa_tecnologias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnologias',
            old_name='tecnologis',
            new_name='tecnologias',
        ),
    ]
