# Generated by Django 4.1.3 on 2022-11-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_rename_tecnologis_tecnologias_tecnologias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnologias',
            old_name='tecnologias',
            new_name='tecnologia',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='caracteristica_empresa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
